-- MySQL Script generated by MySQL Workbench
-- 11/16/16 23:21:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema moovett
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moovett
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moovett` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `moovett` ;

-- -----------------------------------------------------
-- Table `moovett`.`PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`PROFILE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROFILENAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROFILE` VARCHAR(25) NOT NULL,
  `DNI_E` VARCHAR(9) NOT NULL,
  `USERNAME` VARCHAR(25) NOT NULL,
  `NAME` VARCHAR(15) NOT NULL,
  `SURNAME` VARCHAR(40) NOT NULL,
  `FECHA_NAC` DATE NOT NULL,
  `DIRECCION` VARCHAR(50) NOT NULL,
  `COMENTARIO` VARCHAR(500) NULL,
  `NUM_CUENTA` VARCHAR(24) NOT NULL,
  `TIPO_CONTRATO` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(40) NOT NULL,
  `FOTO` MEDIUMBLOB NOT NULL,
  `ACTIVO` TINYINT(1) NOT NULL DEFAULT 1,
  `PASSWD` VARCHAR(15) NOT NULL,
  INDEX `ID_PROFILE_idx` (`PROFILE` ASC),
  UNIQUE INDEX `DNI_E_UNIQUE` (`DNI_E` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `PROFILE`
    FOREIGN KEY (`PROFILE`)
    REFERENCES `moovett`.`PROFILE` (`PROFILENAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `moovett`.`CONTROLLER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`CONTROLLER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTROLLERNAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`ACTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`ACTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACTIONNAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`CLIENTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DNI_C` VARCHAR(9) NOT NULL,
  `NOMBRE_C` VARCHAR(15) NOT NULL,
  `APELLIDOS_C` VARCHAR(40) NOT NULL,
  `FECHA_NAC` DATE NULL,
  `PROFESION` VARCHAR(20) NULL,
  `TELEFONO` INT(11) NULL,
  `DIRECCION` VARCHAR(50) NULL,
  `COMENTARIO` VARCHAR(500) NULL,
  `EMAIL` VARCHAR(30) NULL,
  `ALERTA_FALTA` TINYINT(1) NOT NULL DEFAULT 0,
  `DESEMPLEADO` TINYINT(1) NOT NULL DEFAULT 0,
  `ESTUDIANTE` TINYINT(1) NOT NULL DEFAULT 0,
  `FAMILIAR` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`PARTICULAR_EXTERNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`PARTICULAR_EXTERNO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(20) NOT NULL,
  `APELLIDOS` VARCHAR(30) NOT NULL,
  `TELEFONO` INT(11) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`ESPACIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`ESPACIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`RESERVA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`RESERVA` (
  `ID_ESPACIO` INT NOT NULL,
  `DNI_C` VARCHAR(9) NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PRECIO_ESPACIO` SMALLINT NULL,
  `PRECIO_FISIO` SMALLINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_ESPACIO_idx` (`ID_ESPACIO` ASC),
  CONSTRAINT `ID_ESPACIO`
    FOREIGN KEY (`ID_ESPACIO`)
    REFERENCES `moovett`.`ESPACIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`INSCRIPCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`INSCRIPCION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(20) NULL,
  `APELLIDOS` VARCHAR(30) NULL,
  `ID_EVENTO` INT NULL,
  `ID_ACTIVIDAD` INT NULL,
  `ID_RESERVA` INT NULL,
  `DNI_C` VARCHAR(9) NOT NULL,
  `FECHA` DATE NULL,
  PRIMARY KEY (`ID`, `DNI_C`),
  INDEX `DNI_C_idx` (`DNI_C` ASC),
  INDEX `ID_RESERVA_idx` (`ID_RESERVA` ASC),
  INDEX `NOMBRE_idx` (`NOMBRE` ASC),
  INDEX `APELLIDOS_idx` (`APELLIDOS` ASC),
  CONSTRAINT `DNI_C`
    FOREIGN KEY (`DNI_C`)
    REFERENCES `moovett`.`CLIENTE` (`DNI_C`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NOMBRE`
    FOREIGN KEY (`NOMBRE`)
    REFERENCES `moovett`.`PARTICULAR_EXTERNO` (`NOMBRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `APELLIDOS`
    FOREIGN KEY (`APELLIDOS`)
    REFERENCES `moovett`.`PARTICULAR_EXTERNO` (`APELLIDOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_RESERVA`
    FOREIGN KEY (`ID_RESERVA`)
    REFERENCES `moovett`.`RESERVA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`DOCUMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`DOCUMENTO` (
  `DNI_E` VARCHAR(9) NULL,
  `DNI_C` VARCHAR(9) NULL,
  `ID_INSCRIPCION` INT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(50) NOT NULL,
  `NOMBRE` VARCHAR(50) NOT NULL,
  `CONTENIDO` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `DNI_C_idx` (`DNI_C` ASC),
  INDEX `ID_INSCRIPCION_idx` (`ID_INSCRIPCION` ASC),
  INDEX `DNI_E_idx` (`DNI_E` ASC),
  CONSTRAINT `DNI_E`
    FOREIGN KEY (`DNI_E`)
    REFERENCES `moovett`.`USER` (`DNI_E`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_C`
    FOREIGN KEY (`DNI_C`)
    REFERENCES `moovett`.`CLIENTE` (`DNI_C`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_INSCRIPCION`
    FOREIGN KEY (`ID_INSCRIPCION`)
    REFERENCES `moovett`.`INSCRIPCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`LESIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`LESIONES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` TEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`LESION_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`LESION_CLIENTE` (
  `ID_LESION` INT NOT NULL,
  `DNI_C` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID_LESION`, `DNI_C`),
  INDEX `DNI_C_idx` (`DNI_C` ASC),
  CONSTRAINT `DNI_C`
    FOREIGN KEY (`DNI_C`)
    REFERENCES `moovett`.`CLIENTE` (`DNI_C`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_LESION`
    FOREIGN KEY (`ID_LESION`)
    REFERENCES `moovett`.`LESIONES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`LESION_EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`LESION_EMPLEADO` (
  `ID_LESION` INT NOT NULL,
  `DNI_E` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID_LESION`, `DNI_E`),
  INDEX `DNI_E_idx` (`DNI_E` ASC),
  CONSTRAINT `ID_LESION`
    FOREIGN KEY (`ID_LESION`)
    REFERENCES `moovett`.`LESIONES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_E`
    FOREIGN KEY (`DNI_E`)
    REFERENCES `moovett`.`USER` (`DNI_E`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`EMPLEADO_MIRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`EMPLEADO_MIRA` (
  `DNI_E` VARCHAR(9) NOT NULL,
  `DNI_C` VARCHAR(9) NOT NULL,
  `ID_LESION` INT NOT NULL,
  PRIMARY KEY (`DNI_E`, `DNI_C`, `ID_LESION`),
  INDEX `DNI_C_idx` (`DNI_C` ASC),
  INDEX `ID_LESION_idx` (`ID_LESION` ASC),
  CONSTRAINT `DNI_C`
    FOREIGN KEY (`DNI_C`)
    REFERENCES `moovett`.`LESION_CLIENTE` (`DNI_C`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_LESION`
    FOREIGN KEY (`ID_LESION`)
    REFERENCES `moovett`.`LESION_CLIENTE` (`ID_LESION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_E`
    FOREIGN KEY (`DNI_E`)
    REFERENCES `moovett`.`USER` (`DNI_E`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`EVENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`EVENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(10) NOT NULL,
  `ID_ESPACIO` INT NOT NULL,
  `PRECIO` SMALLINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_ESPACIO_idx` (`ID_ESPACIO` ASC),
  CONSTRAINT `ID_ESPACIO`
    FOREIGN KEY (`ID_ESPACIO`)
    REFERENCES `moovett`.`ESPACIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`CATEGORIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`DESCUENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`DESCUENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` TEXT NOT NULL,
  `TIPO` VARCHAR(10) NOT NULL,
  `CANTIDAD` FLOAT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `TIPO_idx` (`TIPO` ASC),
  CONSTRAINT `TIPO`
    FOREIGN KEY (`TIPO`)
    REFERENCES `moovett`.`CATEGORIA` (`TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`ACTIVIDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`ACTIVIDAD` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(10) NOT NULL,
  `ID_ESPACIO` INT NOT NULL,
  `ID_DESCUENTO` INT NOT NULL,
  `CAPACIDAD` SMALLINT NOT NULL,
  `PRECIO` SMALLINT NOT NULL,
  `TIPO` VARCHAR(10) NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_ESPACIO_idx` (`ID_ESPACIO` ASC),
  INDEX `TIPO_idx` (`TIPO` ASC),
  INDEX `ID_DESCUENTO_idx` (`ID_DESCUENTO` ASC),
  CONSTRAINT `ID_ESPACIO`
    FOREIGN KEY (`ID_ESPACIO`)
    REFERENCES `moovett`.`ESPACIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_DESCUENTO`
    FOREIGN KEY (`ID_DESCUENTO`)
    REFERENCES `moovett`.`DESCUENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TIPO`
    FOREIGN KEY (`TIPO`)
    REFERENCES `moovett`.`CATEGORIA` (`TIPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`HORARIO_TEMPORADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`HORARIO_TEMPORADA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DIA_INICIO` DATE NOT NULL,
  `DIA_FIN` DATE NOT NULL,
  `NOMBRE_TEMP` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`, `DIA_INICIO`, `DIA_FIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`RANGO_HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`RANGO_HORARIO` (
  `DIA_S` VARCHAR(10) NOT NULL,
  `HORA_APERTURA` TIME NOT NULL,
  `HORA_CIERRE` TIME NOT NULL,
  `ID_TEMPORADA` INT NOT NULL,
  `DIA_INICIO` DATE NOT NULL,
  `DIA_FIN` DATE NOT NULL,
  PRIMARY KEY (`DIA_S`, `HORA_APERTURA`, `HORA_CIERRE`),
  INDEX `ID_TEMPORADA_idx` (`ID_TEMPORADA` ASC),
  INDEX `DIA_INICIO_idx` (`DIA_INICIO` ASC),
  INDEX `DIA_FIN_idx` (`DIA_FIN` ASC),
  CONSTRAINT `ID_TEMPORADA`
    FOREIGN KEY (`ID_TEMPORADA`)
    REFERENCES `moovett`.`HORARIO_TEMPORADA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DIA_INICIO`
    FOREIGN KEY (`DIA_INICIO`)
    REFERENCES `moovett`.`HORARIO_TEMPORADA` (`DIA_INICIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DIA_FIN`
    FOREIGN KEY (`DIA_FIN`)
    REFERENCES `moovett`.`HORARIO_TEMPORADA` (`DIA_FIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`HORAS_POSIBLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`HORAS_POSIBLES` (
  `DIA` DATE NOT NULL,
  `HORA_INICIO` TIME NOT NULL,
  `HORA_FIN` TIME NOT NULL,
  `DIA_S` VARCHAR(10) NOT NULL,
  `HORA_APERTURA` TIME NOT NULL,
  `HORA_CIERRE` TIME NOT NULL,
  PRIMARY KEY (`DIA`, `HORA_INICIO`, `HORA_FIN`),
  INDEX `DIA_S_idx` (`DIA_S` ASC),
  INDEX `HORA_APERTURA_idx` (`HORA_APERTURA` ASC),
  INDEX `HORA_CIERRE_idx` (`HORA_CIERRE` ASC),
  CONSTRAINT `DIA_S`
    FOREIGN KEY (`DIA_S`)
    REFERENCES `moovett`.`RANGO_HORARIO` (`DIA_S`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `HORA_APERTURA`
    FOREIGN KEY (`HORA_APERTURA`)
    REFERENCES `moovett`.`RANGO_HORARIO` (`HORA_APERTURA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `HORA_CIERRE`
    FOREIGN KEY (`HORA_CIERRE`)
    REFERENCES `moovett`.`RANGO_HORARIO` (`HORA_CIERRE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`SESION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`SESION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_ESPACIO` INT NOT NULL,
  `ID_EVENTO` INT NULL,
  `ID_ACTIVIDAD` INT NULL,
  `DNI_E` VARCHAR(9) NOT NULL,
  `DIA` DATE NOT NULL,
  `HORA_INICIO` TIME NOT NULL,
  `HORA_FIN` TIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `DNI_E_idx` (`DNI_E` ASC),
  INDEX `ID_EVENTO_idx` (`ID_EVENTO` ASC),
  INDEX `ID_ACTIVIDAD_idx` (`ID_ACTIVIDAD` ASC),
  INDEX `DIA_idx` (`DIA` ASC),
  INDEX `HORA_INICIO_idx` (`HORA_INICIO` ASC),
  INDEX `HORA_FIN_idx` (`HORA_FIN` ASC),
  CONSTRAINT `DNI_E`
    FOREIGN KEY (`DNI_E`)
    REFERENCES `moovett`.`USER` (`DNI_E`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_EVENTO`
    FOREIGN KEY (`ID_EVENTO`)
    REFERENCES `moovett`.`EVENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_ACTIVIDAD`
    FOREIGN KEY (`ID_ACTIVIDAD`)
    REFERENCES `moovett`.`ACTIVIDAD` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_ESPACIO`
    FOREIGN KEY (`ID_ESPACIO`)
    REFERENCES `moovett`.`ESPACIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DIA`
    FOREIGN KEY (`DIA`)
    REFERENCES `moovett`.`HORAS_POSIBLES` (`DIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `HORA_INICIO`
    FOREIGN KEY (`HORA_INICIO`)
    REFERENCES `moovett`.`HORAS_POSIBLES` (`HORA_INICIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `HORA_FIN`
    FOREIGN KEY (`HORA_FIN`)
    REFERENCES `moovett`.`HORAS_POSIBLES` (`HORA_FIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`PAGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`PAGO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `METODO_PAGO` VARCHAR(20) NOT NULL,
  `FECHA` DATE NOT NULL,
  `PERIODICIDAD` VARCHAR(45) NOT NULL,
  `CANTIDAD` SMALLINT NOT NULL,
  `ID_INSCRIPCION` INT NULL,
  `ID_RESERVA` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_INSCRIPCION_idx` (`ID_INSCRIPCION` ASC),
  INDEX `ID_RESERVA_idx` (`ID_RESERVA` ASC),
  CONSTRAINT `ID_INSCRIPCION`
    FOREIGN KEY (`ID_INSCRIPCION`)
    REFERENCES `moovett`.`INSCRIPCION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_RESERVA`
    FOREIGN KEY (`ID_RESERVA`)
    REFERENCES `moovett`.`RESERVA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`ASISTENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`ASISTENCIA` (
  `ID_CLIENTE` INT NOT NULL,
  `ID_SESION` INT NOT NULL,
  `ASISTE` TINYINT(1) NULL,
  PRIMARY KEY (`ID_CLIENTE`, `ID_SESION`),
  CONSTRAINT `ID_CLIENTE`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `moovett`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_SESION`
    FOREIGN KEY ()
    REFERENCES `moovett`.`SESION` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`ALERTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`ALERTA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` TEXT NOT NULL,
  `ID_SESION` INT NULL,
  `DNI_E` VARCHAR(9) NULL,
  `ID_PAGO` INT NULL,
  `ID_CLIENTE` INT NULL,
  `ID_SESION` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_PAGO_idx` (`ID_PAGO` ASC),
  INDEX `ID_CLIENTE_idx` (`ID_CLIENTE` ASC),
  INDEX `ID_SESION_idx` (`ID_SESION` ASC),
  CONSTRAINT `DNI_E`
    FOREIGN KEY ()
    REFERENCES `moovett`.`USER` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PAGO`
    FOREIGN KEY (`ID_PAGO`)
    REFERENCES `moovett`.`PAGO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_CLIENTE`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `moovett`.`ASISTENCIA` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_SESION`
    FOREIGN KEY (`ID_SESION`)
    REFERENCES `moovett`.`ASISTENCIA` (`ID_SESION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`NOTIFICACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`NOTIFICACION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` TEXT NOT NULL,
  `DNI_E` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `DNI_E_idx` (`DNI_E` ASC),
  CONSTRAINT `DNI_E`
    FOREIGN KEY (`DNI_E`)
    REFERENCES `moovett`.`USER` (`DNI_E`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`RECIBE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`RECIBE` (
  `ID_NOTIFICACION` INT NOT NULL,
  `DNI_C` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID_NOTIFICACION`, `DNI_C`),
  INDEX `DNI_C_idx` (`DNI_C` ASC),
  CONSTRAINT `ID_NOTIFICACION`
    FOREIGN KEY (`ID_NOTIFICACION`)
    REFERENCES `moovett`.`NOTIFICACION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_C`
    FOREIGN KEY (`DNI_C`)
    REFERENCES `moovett`.`CLIENTE` (`DNI_C`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`PERCIBE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`PERCIBE` (
  `ID_ALERTA` INT NOT NULL,
  `DNI_E` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID_ALERTA`, `DNI_E`),
  INDEX `DNI_E_idx` (`DNI_E` ASC),
  CONSTRAINT `ID_ALERTA`
    FOREIGN KEY (`ID_ALERTA`)
    REFERENCES `moovett`.`ALERTA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_E`
    FOREIGN KEY (`DNI_E`)
    REFERENCES `moovett`.`USER` (`DNI_E`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`HORA_FISIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`HORA_FISIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_RESERVA` INT NOT NULL,
  `DIA_F` DATE NOT NULL,
  `HORA_I` TIME NOT NULL,
  `HORA_F` TIME NOT NULL,
  INDEX `ID_RESERVA_idx` (`ID_RESERVA` ASC),
  PRIMARY KEY (`ID`),
  CONSTRAINT `ID_RESERVA`
    FOREIGN KEY (`ID_RESERVA`)
    REFERENCES `moovett`.`RESERVA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`FACTURA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PAGO` INT NOT NULL,
  `FECHA` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_PAGO_idx` (`ID_PAGO` ASC),
  CONSTRAINT `ID_PAGO`
    FOREIGN KEY (`ID_PAGO`)
    REFERENCES `moovett`.`PAGO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`LINEA_FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`LINEA_FACTURA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_FACTURA` INT NOT NULL,
  `PRODUCTO` VARCHAR(40) NULL,
  `CANTIDAD` SMALLINT NULL,
  `PRECIO` SMALLINT NULL,
  PRIMARY KEY (`ID`, `ID_FACTURA`),
  INDEX `ID_FACTURA_idx` (`ID_FACTURA` ASC),
  CONSTRAINT `ID_FACTURA`
    FOREIGN KEY (`ID_FACTURA`)
    REFERENCES `moovett`.`FACTURA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`RECIBO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`RECIBO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PAGO` INT NOT NULL,
  `PRODUCTO` VARCHAR(40) NOT NULL,
  `PRECIO` SMALLINT NOT NULL,
  `CANTIDAD` SMALLINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_PAGO_idx` (`ID_PAGO` ASC),
  CONSTRAINT `ID_PAGO`
    FOREIGN KEY (`ID_PAGO`)
    REFERENCES `moovett`.`PAGO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`CAJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`CAJA` (
  `ID_PAGO` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EFECTIVO_INICIAL` INT(11) NOT NULL,
  `CANTIDAD` INT(11) NOT NULL,
  `EFECTIVO_FINAL` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_PAGO_idx` (`ID_PAGO` ASC),
  CONSTRAINT `ID_PAGO`
    FOREIGN KEY (`ID_PAGO`)
    REFERENCES `moovett`.`PAGO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`CLIENTE_EXTERNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`CLIENTE_EXTERNO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DNI_NIF` VARCHAR(9) NOT NULL,
  `NOMBRE` VARCHAR(80) NOT NULL,
  `APELLIDO` VARCHAR(40) NULL,
  `TELEFONO` INT(11) NULL,
  `EMAIL` VARCHAR(30) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`SERVICIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`SERVICIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FECHA` DATE NOT NULL,
  `COSTE` INT(11) NOT NULL,
  `ID_PAGO` INT NOT NULL,
  `DNI_NIF` VARCHAR(9) NOT NULL,
  `DESCRIPCION` TEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_PAGO_idx` (`ID_PAGO` ASC),
  INDEX `DNI_NIF_idx` (`DNI_NIF` ASC),
  CONSTRAINT `ID_PAGO`
    FOREIGN KEY (`ID_PAGO`)
    REFERENCES `moovett`.`PAGO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DNI_NIF`
    FOREIGN KEY (`DNI_NIF`)
    REFERENCES `moovett`.`CLIENTE_EXTERNO` (`DNI_NIF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`APLICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`APLICA` (
  `ID_DESCUENTO` INT NOT NULL,
  `ID_ACTIVIDAD` INT NOT NULL,
  PRIMARY KEY (`ID_DESCUENTO`, `ID_ACTIVIDAD`),
  INDEX `ID_ACTIVIDAD_idx` (`ID_ACTIVIDAD` ASC),
  CONSTRAINT `ID_DESCUENTO`
    FOREIGN KEY (`ID_DESCUENTO`)
    REFERENCES `moovett`.`DESCUENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_ACTIVIDAD`
    FOREIGN KEY (`ID_ACTIVIDAD`)
    REFERENCES `moovett`.`ACTIVIDAD` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`PERMISSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`PERMISSION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CONTROLLER` VARCHAR(25) NOT NULL,
  `ACTION` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ACTION_idx` (`ACTION` ASC),
  INDEX `CONTROLLER_idx` (`CONTROLLER` ASC),
  CONSTRAINT `CONTROLLER`
    FOREIGN KEY (`CONTROLLER`)
    REFERENCES `moovett`.`CONTROLLER` (`CONTROLLERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ACTION`
    FOREIGN KEY (`ACTION`)
    REFERENCES `moovett`.`ACTION` (`ACTIONNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`USER_PERMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`USER_PERMS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERID` INT NOT NULL,
  `PERMISSION` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `USERID_idx` (`USERID` ASC),
  INDEX `PERMISSION_idx` (`PERMISSION` ASC),
  CONSTRAINT `USERID`
    FOREIGN KEY (`USERID`)
    REFERENCES `moovett`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PERMISSION`
    FOREIGN KEY (`PERMISSION`)
    REFERENCES `moovett`.`PERMISSION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovett`.`PROFILE_PERMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovett`.`PROFILE_PERMS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PROFILEID` INT NOT NULL,
  `PERMISSION` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `PROFILEID_idx` (`PROFILEID` ASC),
  INDEX `PERMISION_idx` (`PERMISSION` ASC),
  CONSTRAINT `PROFILEID`
    FOREIGN KEY (`PROFILEID`)
    REFERENCES `moovett`.`PROFILE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PERMISION`
    FOREIGN KEY (`PERMISSION`)
    REFERENCES `moovett`.`PERMISSION` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'moovett' IDENTIFIED BY 'moovett';

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE `moovett`.* TO 'moovett';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
